language: en
pipeline:
- name: WhitespaceTokenizer
- name: sentiment.SentimentAnalyzer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: CRFEntityExtractor
- name: DIETClassifier
  entity_recognition: false
  batch_strategy: sequence
  epochs: 100
- name: EntitySynonymMapper
- name: FallbackClassifier
  threshold: 0.4
  ambiguity_threshold: 0.3
policies:
- name: MemoizationPolicy
- name: TEDPolicy
  max_history: 5
  epochs: 100
- name: FormPolicy
- name: RulePolicy
  core_fallback_threshold: 0.3
  core_fallback_action_name: action_default_fallback
